<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CleanArchitecture.Infrastructure</RootNamespace>
    <AssemblyName>CleanArchitecture.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Extensions.Resilience" />
    <ProjectReference Include="../Application/Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="CleanArchitecture.Database.SqlServer" />
    <InternalsVisibleTo Include="CleanArchitecture.Database.SQLite" />
    <InternalsVisibleTo Include="CleanArchitecture.Database.Oracle" />
  </ItemGroup>
</Project>
