<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsTestProject>true</IsTestProject><RootNamespace>CleanArchitecture.Web.AcceptanceTests</RootNamespace><AssemblyName>CleanArchitecture.Web.AcceptanceTests</AssemblyName></PropertyGroup>
  <ItemGroup><PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" /><PackageReference Include="Microsoft.Playwright" /><PackageReference Include="Shouldly" />
  </ItemGroup>
</Project>
