<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>CleanArchitecture.Application.FunctionalTests</RootNamespace>
    <AssemblyName>CleanArchitecture.Application.FunctionalTests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <ProjectReference Include="../../src/Web/Web.csproj" />
  </ItemGroup>
</Project>