<Project Sdk="Aspire.AppHost.Sdk/13.5.3">
  <PropertyGroup><OutputType>Exe</OutputType><RootNamespace>CleanArchitecture.AppHost</RootNamespace><AssemblyName>CleanArchitecture.AppHost</AssemblyName></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <ProjectReference Include="../Shared/Shared.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="../Web/Web.csproj" />
  </ItemGroup>
</Project>
