<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>CleanArchitecture.Application.UnitTests</RootNamespace>
    <AssemblyName>CleanArchitecture.Application.UnitTests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Shouldly" />
    <ProjectReference Include="../../src/Application/Application.csproj" />
  </ItemGroup>
</Project>