<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>CleanArchitecture.Database.Tests</RootNamespace>
    <AssemblyName>CleanArchitecture.Database.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Aspire.Hosting.Testing" />
    <ProjectReference Include="../SqlServer/SqlServer.csproj" />
    <ProjectReference Include="../SQLite/SQLite.csproj" />
    <ProjectReference Include="../Oracle/Oracle.csproj" />
    <ProjectReference Include="../TestAppHost/TestAppHost.csproj" />
    <ProjectReference Include="../../../tests/Infrastructure.IntegrationTests/Infrastructure.IntegrationTests.csproj" />
    <ProjectReference Include="../../../tests/Application.FunctionalTests/Application.FunctionalTests.csproj" />
    <Using Include="NUnit.Framework" />
    <Using Include="Shouldly" />
    <None Update="Fixtures/*.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
